name: fastnanquantile-dev
channels:
    - conda-forge
dependencies:
    - python>=3.8
    # required
    - numba
    - numpy
    - xarray[parallel]
    
    # testing
    - pytest
    - pytest-cov
    - coverage
    
    # linting
    - flake8

    # styling
    - black
    #- pre-commit
    - pip
    - pip:
        .
